[package]
name = "kvs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
predicates = "3.1.0"
assert_cmd = "0.11.0"
clap = { version = "4.5.2", features = ["derive"] }
